# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='longitude',
        ),
        migrations.AddField(
            model_name='consumer',
            name='password',
            field=models.CharField(default='1234', max_length=50),
        ),
    ]
