# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='url',
            field=models.CharField(default='store.img', max_length=1000),
        ),
    ]
