# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_producer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='farmurl',
            field=models.CharField(default='farm.img', max_length=1000),
        ),
    ]
