# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20171102_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminoffer',
            name='producers',
            field=models.ManyToManyField(to='store.Producer'),
        ),
    ]
