# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_adminoffer_producers'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='password',
            field=models.CharField(default='1234', max_length=50),
        ),
    ]
