# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-05 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_producer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.Payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='state',
            field=models.TextField(default='PENDIENTE'),
        ),
    ]
