# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-05 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20171105_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='state',
        ),
        migrations.AddField(
            model_name='order_item',
            name='state',
            field=models.TextField(default='PENDIENTE'),
        ),
    ]
